;;; Automatically generated by ‘recentf’ on Mon Nov  4 02:44:38 2019.

(setq recentf-list
      '(
        "/home/jaha/.emacs.d/data/treemacs/persist.org"
        "/home/jaha/projects/kinomax/docker-compose.yml"
        "/home/jaha/projects/kinomax/docker/dev/config/vhost.conf"
        "/home/jaha/projects/shopguide-backend-xcart/docker/nginx/nginx.conf"
        "/home/jaha/projects/shopguide-backend-xcart/docker/nginx/Dockerfile"
        "/home/jaha/projects/kinomax/.gitignore"
        "/home/jaha/projects/kinomax/.env"
        "/home/jaha/projects/kinomax/docker/dev/web.Dockerfile"
        "/home/jaha/projects/shopguide-backend-xcart/docker-compose.yml"
        "/home/jaha/projects/kinomax/docker/dev/config/vhost.conf.example"
        "/home/jaha/projects/kinomax/Makefile"
        "/home/jaha/projects/kinomax/readme.md"
        "/home/jaha/projects/kinomax/.env.example"
        "/home/jaha/projects/kinomax/readme-admin-lte.md"
        "/home/jaha/projects/kinomax/docker/dev/db.Dockerfile"
        "/home/jaha/projects/kinomax/docker/dev/app.Dockerfile"
        "/home/jaha/.ssh/config"
        "/home/jaha/projects/kinomax/config/auth.php"
        "/home/jaha/.emacs.d/init.el"
        "/home/jaha/.emacs.d/elpa/editorconfig-20191025.806/editorconfig-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
