;;; Automatically generated by ‘recentf’ on Fri Oct 25 01:27:43 2019.

(setq recentf-list
      '(
        "/home/jaha/.emacs.d/data/treemacs/persist.org"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/View/Form/Profile/FinancialInfo.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/View/Form/Profile/Register.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/View/Form/Profile/Vendor.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/ProfileTransaction.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/Profile.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/CompanyFieldValue.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/CompanyFieldTranslation.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/CompanyFieldStorage.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/CompanyFieldOptionTranslation.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/CompanyFieldOption.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Model/CompanyField.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/View/Form/CompanyAddress.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Controller/Admin/CompanyAddress.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Controller/Admin/Attribute.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Controller/Admin/AddressBook.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/View/Address/OrderModify.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/XC/MultiVendor/Controller/Admin/AddPinCodes.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Module/Zebrains/DHL/Model/Shipping/Mapper/ShipmentValidation/InputMapper.php"
        "/home/jaha/projects/shopguide-backend-xcart/classes/XLite/Model/Shipping.php"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
