;;; Automatically generated by ‘recentf’ on Fri Sep 20 00:28:10 2019.

(setq recentf-list
      '(
        "/home/jahangir/.emacs.d/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
